package com.imovelferias.model.announce.title

enum class Items {
    GYM, PETS, KITCHEN, DEFICIENT_ADAPT, HEATER, ELEVATOR, IRON, STOVE, FREEZER, REFRIGERATOR,
    WHIRLPOOL, WIFI, NO_SMOKE, FIREPLACE, DISHWASHER, BLENDER, WASHING_MACHINE, MICROWAVES, PARTY,
    BEDDING, STEAM_ROOM, TV, CABLE_TV, KITCHEN_UTENSILS, BARBECUE_UTENSILS, COVERED_GARAGE, SEA_VIEW,
    POOL, BEACH_CHAIR, GRILL, GATED_COMMUNITY, DRYING_MACHINE, BATH_TOWEL, MOUNTAIN_VIEW
}